services:
  nextcloud_db:
    image: mariadb
    restart: unless-stopped
    environment:
      # The password will appear in the initial logs
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      # There is no need to create a Nextcloud account here. In the browser installer just provide the root creds,
      # and Nextcloud will create an account and database for itself and save it in config.php.
      # See https://docs.nextcloud.com/server/stable/admin_manual/installation/installation_wizard.html#database-choice
      #MYSQL_DATABASE: nextcloud
      #MYSQL_USER: nextcloud_db_user
      #MYSQL_PASSWORD: nextcloud_db_password
    volumes:
      - ./nextcloud_db:/var/lib/mysql
    networks:
      - nextcloud-net
    # copied from https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 4
  nextcloud:
    image: nextcloud:stable
    restart: unless-stopped
    depends_on:
      nextcloud_db:
        condition: service_healthy
    ports:
      - "8080:80"
    # environment:
    # No need to specify those, see above.
    #   MYSQL_DATABASE: nextcloud
    #   MYSQL_USER: nextcloud
    #   MYSQL_PASSWORD: nextcloud_password
    # To be specified in the browser installer:
    #   MYSQL_HOST: nextcloud_db
    #   NEXTCLOUD_ADMIN_USER: admin
    #   NEXTCLOUD_ADMIN_PASSWORD: admin_password
    volumes:
      - ./nextcloud:/var/www/html
    networks:
      - nextcloud-net
networks:
  nextcloud-net:
    driver: bridge
